apiVersion: v1
data:
  JAVA_AGENT_ENABLED: 'true'
  MESSAGE: hello dev-demo world
  PROFILE: dev
  VERSION: v0.4.47
kind: ConfigMap
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
