apiVersion: v1
data:
  JAVA_AGENT_ENABLED: 'true'
  MESSAGE: hello prod-demo world
  PROFILE: prod
  VERSION: v0.4.35
kind: ConfigMap
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring
