apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: sample-spring
    app.kubernetes.io/name: sample-spring
  name: sample-spring-preview
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: sample-spring-preview.demo.spic.me
      http:
        paths:
          - backend:
              serviceName: sample-spring-preview
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - sample-spring-preview.demo.spic.me
      secretName: sample-spring-preview-mzdev-tls
