apiVersion: v1
data:
  FAULT_RATE: '2'
  MESSAGE: hello prod-demo world
  PROFILE: prod
  VERSION: v0.4.34
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
