apiVersion: v1
data:
  JAVA_AGENT_ENABLED: 'true'
  MESSAGE: hello prod-demo world
  PROFILE: prod
  VERSION: v0.4.29
kind: ConfigMap
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
