apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: sample-tomcat.demo.mzdev.be
      http:
        paths:
          - backend:
              serviceName: sample-tomcat
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - sample-tomcat.demo.mzdev.be
      secretName: sample-tomcat-mzdev-tls
