apiVersion: v1
data:
  JAVA_AGENT_ENABLED: "true"
  MESSAGE: hello dev-demo world
  PROFILE: dev
  VERSION: v0.4.15
kind: ConfigMap
metadata:
  labels:
    app: sample-tomcat
    app.kubernetes.io/name: sample-tomcat
  name: sample-tomcat
