apiVersion: v1
data:
  FAULT_RATE: '5'
  MESSAGE: hello dev-demo world
  PROFILE: dev
  VERSION: v0.4.48
kind: ConfigMap
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
