apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: sample-node
    app.kubernetes.io/name: sample-node
  name: sample-node
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sample-node
  strategy:
    blueGreen:
      activeService: sample-node
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      previewService: sample-node-preview
  template:
    metadata:
      labels:
        app: sample-node
        app.kubernetes.io/name: sample-node
        version: v0.4.45
    spec:
      containers:
      - env:
        - name: CONFIGMAP_HASH
          value: cb679e7b2adff0597ef2f527b3f7bea1
        - name: SECRET_HASH
          value: ''
        envFrom:
        - configMapRef:
            name: sample-node
        image: nalbam/sample-node:v0.4.45
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sample-node
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 110m
            memory: 134Mi
          requests:
            cpu: 100m
            memory: 120Mi
