apiVersion: v1
data:
  MESSAGE: hello dev-demo world
  PROFILE: dev
  VERSION: v0.3.7
kind: ConfigMap
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
