apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: sample-webpack-dev.demo.spic.me
      http:
        paths:
          - backend:
              serviceName: sample-webpack
              servicePort: 80
            path: /
  tls:
    - hosts:
        - sample-webpack-dev.demo.spic.me
      secretName: sample-webpack-tls
