apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nalbam-docs
    app.kubernetes.io/name: nalbam-docs
  name: nalbam-docs
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nalbam-docs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nalbam-docs
        app.kubernetes.io/name: nalbam-docs
        version: v0.0.21
    spec:
      containers:
        - image: nalbam/docs:v0.0.21
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 1948
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nalbam-docs
          ports:
            - name: http
              containerPort: 1948
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 1948
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 110m
              memory: 134Mi
