apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: nalbam-docs
    app.kubernetes.io/name: nalbam-docs
  name: nalbam-docs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: docs.demo.spic.me
      http:
        paths:
          - backend:
              serviceName: nalbam-docs
              servicePort: 80
            path: /
  tls:
    - hosts:
        - docs.demo.spic.me
      secretName: docs-mzdev-tls
