apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-webpack
    app.kubernetes.io/name: sample-webpack
  name: sample-webpack
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: "80"
  selector:
    app: sample-webpack
