apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: sample-web
    app.kubernetes.io/name: sample-web
  name: sample-web
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: sample-web.demo.spic.me
      http:
        paths:
          - backend:
              serviceName: sample-web
              servicePort: 80
            path: /
  tls:
    - hosts:
        - sample-web.demo.spic.me
      secretName: sample-web--tls
